name: Build SF8008 HiSilicon Kernel Modules

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y gcc-arm-linux-gnueabihf make git bc bison flex libssl-dev libncurses-dev

    - name: Clone kernel source
      run: |
        git clone --depth=1 https://github.com/leandrotsampa/hisilicon-kernel kernel

    - name: Copy config
      run: |
        cp sf8008.config kernel/.config

    - name: Build kernel modules
      working-directory: kernel
      run: |
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- olddefconfig
        make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- modules -j$(nproc)

    - name: Archive .ko modules
      run: |
        mkdir -p out
        find kernel -name '*.ko' -exec cp {} out/ \;
        zip -r sf8008_modules.zip out/

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sf8008_modules
        path: sf8008_modules.zip
