name: Build SF8008 Kernel

on:
  workflow_dispatch:

jobs:
  build-kernel:
    runs-on: ubuntu-22.04

    env:
      ARCH: arm
      CROSS_COMPILE: arm-linux-gnueabihf-

    steps:
      - name: Checkout kernel source
        uses: actions/checkout@v4

      - name: Set up toolchain and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            gcc-arm-linux-gnueabihf \
            make \
            bc \
            libncurses-dev \
            bison \
            flex \
            libssl-dev \
            cpio \
            u-boot-tools \
            device-tree-compiler \
            build-essential

      - name: Copy sf8008 config to kernel/.config
        run: |
          wget https://raw.githubusercontent.com/jinglingxiaoguin/sf8008-hi3136-build/main/sf8008.config -O .config

      - name: Build kernel
        working-directory: ./kernel
        run: |
          make olddefconfig
          make -j$(nproc)

      - name: Pack output
        run: |
          mkdir -p output
          cp kernel/arch/arm/boot/zImage output/
          cp kernel/arch/arm/boot/dts/*.dtb output/ || true
          find kernel -name "*.ko" -exec cp {} output/ \;

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: sf8008-kernel-output
          path: output
