name: Build OpenATV for SF8008

on:
  workflow_dispatch:

jobs:
  build:
    name: Build SF8008 Image
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake bison bzip2 chrpath cmake coreutils cpio curl cvs \
            debianutils default-jre default-jre-headless diffstat flex g++ gawk gcc gcc-12 \
            gcc-multilib g++-multilib gettext git gzip help2man info iputils-ping java-common \
            libc6-dev libglib2.0-dev libncurses-dev libperl4-corelibs-perl libproc-processtable-perl \
            libsdl1.2-dev libserf-dev libtool libxml2-utils make ncurses-bin patch perl pkg-config \
            psmisc python3 python3-git python3-jinja2 python3-pexpect python3-pip python3-setuptools \
            quilt socat sshpass subversion tar texi2html texinfo unzip wget xsltproc xterm xz-utils \
            zip zlib1g-dev zstd fakeroot lz4 git-lfs

      - name: Set up python and shell
        run: |
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python2 1
          sudo update-alternatives --install /usr/bin/python python /usr/bin/python3 2
          sudo update-alternatives --set python /usr/bin/python3
          sudo ln -sf /bin/bash /bin/sh
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf
          sudo sysctl -n -w fs.inotify.max_user_watches=524288
          echo 'kernel.apparmor_restrict_unprivileged_userns=0' | sudo tee /etc/sysctl.d/60-apparmor-namespace.conf
          sudo sysctl --system

      - name: Clone build environment
        run: |
          git clone https://github.com/oe-alliance/build-enviroment.git -b 5.5.1

          cd openatv
          make update

      - name: Add dvb-hisi driver recipe
        run: |
          mkdir -p openatv/meta-local/recipes-dvb/dvb-hisi/files
          cat << 'EOF' > openatv/meta-local/recipes-dvb/dvb-hisi/dvb-hisi_git.bb
DESCRIPTION = "HiSilicon DVB driver from leandrotsampa"
LICENSE = "GPLv2"
LIC_FILES_CHKSUM = "file://COPYING;md5=751419260aa954499f7abaabaa882bbe"

SRCREV = "${AUTOREV}"
PV = "1.0+git${SRCPV}"
PR = "r0"

SRC_URI = "git://github.com/leandrotsampa/dvb-hisi.git;protocol=https;branch=main"
S = "${WORKDIR}/git"

inherit module

DEPENDS += "virtual/kernel"

EXTRA_OEMAKE += "KERNELDIR=${STAGING_KERNEL_DIR}"

do_compile() {
    oe_runmake
}

do_install() {
    install -d ${D}${nonarch_base_libdir}/modules/${KERNEL_VERSION}/extra
    install -m 0644 *.ko ${D}${nonarch_base_libdir}/modules/${KERNEL_VERSION}/extra
}
EOF

      - name: Build Enigma2 image
        run: |
          cd openatv
          MACHINE=sf8008 DISTRO=openatv DISTRO_TYPE=release make enigma2-image

      - name: Upload image (optional)
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: sf8008-enigma2-image
          path: openatv/builds/openatv/release/sf8008/tmp/deploy/images/sf8008/
