name: Build OpenATV for SF8008

on:
  workflow_dispatch:

jobs:
  build:
    name: Build SF8008 Image
    runs-on: ubuntu-22.04
    timeout-minutes: 360

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v4

      - name: Install required packages
        run: |
          sudo apt-get update
          sudo apt-get install -y autoconf automake bison bzip2 chrpath cmake \
            coreutils cpio curl cvs debianutils default-jre default-jre-headless \
            diffstat flex g++ gawk gcc gcc-12 gcc-multilib g++-multilib gettext \
            git gzip help2man info iputils-ping java-common libc6-dev \
            libglib2.0-dev libncurses-dev libperl4-corelibs-perl \
            libproc-processtable-perl libtool libtool-bin locales \
            lz4 nano ninja-build openssh-client patch pkg-config \
            python3 python3-distutils python3-git python3-jinja2 \
            python3-pip python3-pexpect python3-ply python3-subunit \
            python3-virtualenv rsync screen socat subversion texi2html \
            texinfo unzip wget xmlto xz-utils zstd

      - name: Clone oe-alliance-core
        run: |
          git clone https://github.com/OpenATV/oe-alliance-core.git
          cd oe-alliance-core
          git checkout 5.5.1

      - name: Clone LeandroTsampa's kernel and dvb-hisi
        run: |
          cd oe-alliance-core
          mkdir -p meta-mysf8008/recipes-kernel/linux
          git clone https://github.com/leandrotsampa/linux-4.4.35.git \
            meta-mysf8008/recipes-kernel/linux/linux-leandrotsampa
          git clone https://github.com/leandrotsampa/dvb-hisi.git \
            meta-mysf8008/recipes-dvb/dvb-hisi

      - name: Apply custom layer to bblayers.conf and local.conf
        run: |
          cd oe-alliance-core
          echo 'BBLAYERS += "${TOPDIR}/meta-mysf8008"' >> conf/bblayers.conf
          echo 'MACHINE = "sf8008"' > conf/local.conf
          echo 'DISTRO = "openatv"' >> conf/local.conf
          echo 'IMAGE_FSTYPES += "tar.xz"' >> conf/local.conf

      - name: Build image
        run: |
          cd oe-alliance-core
          source ./env.source
          MACHINE=sf8008 DISTRO=openatv make image -j$(nproc)

      - name: Archive built image
        uses: actions/upload-artifact@v4
        with:
          name: sf8008-openatv-image
          path: |
            oe-alliance-core/builds/sf8008/tmp/deploy/images/sf8008/
