name: Build hi3136.ko for SF8008

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build hi3136 module

    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y git wget build-essential bc flex bison libssl-dev libncurses-dev u-boot-tools

      - name: Clone kernel
        run: |
          git clone --depth=1 https://github.com/leandrotsampa/hisilicon-kernel.git
          cd hisilicon-kernel
          wget https://raw.githubusercontent.com/你的用户名/你的仓库名/main/sf8008.config -O .config
          make ARCH=arm olddefconfig
          make ARCH=arm CROSS_COMPILE=arm-linux-gnueabi- modules_prepare

      - name: Clone dvb-hisi
        run: |
          git clone https://github.com/leandrotsampa/dvb-hisi.git

      - name: Build module
        run: |
          export KDIR=$PWD/hisilicon-kernel
          export ARCH=arm
          export CROSS_COMPILE=arm-linux-gnueabi-
          make -C $KDIR M=$PWD/dvb-hisi modules

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hi3136-ko
          path: dvb-hisi/*.ko
